Algoritmo "Numero-Dobro-Triplo"
//  Faça um algoritmo que o usuário digite um número e obtenha
//  como resultado o dobro e o triplo do número digitado
Var
   numero, numeroDobro, numeroTriplo: real


Inicio
      escreva("Digite um número: ")
      leia(numero)
      numeroDobro <- numero * 2
      numeroTriplo <- numero * 3
      escreval("O dobro do número escolhido é:", numeroDobro)
      escreval("E o triplo é: ", numeroTriplo)

Fimalgoritmo